# -*- coding: utf-8 -*-
"""Planets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A7MOCrBjFmdve_wjUs7gWTgJhvEcb-0t
"""

# Commented out IPython magic to ensure Python compatibility.
# %reload_ext autoreload
# %autoreload 2
# %matplotlib inline

from fastai.vision import *

path = untar_data(URLs.PLANET_SAMPLE)

path.ls()
path_img = path/'train'
path_img.ls()[:5]

df = pd.read_csv(path/'labels.csv')

src  = ImageList.from_csv(path,csv_name='labels.csv',folder='train',suffix='.jpg')

src.items

src = src.split_by_rand_pct(0.2)
src

src = src.label_from_df(label_delim = ' ')
src

img = open_image(path_img.ls()[0])
img.data.shape

size = 256
def get_data(size,bs=48):
  return src.transform(get_transforms(flip_vert=True, max_lighting=0.1, max_zoom=1.05, max_warp=0.),size=size).databunch(bs=bs).normalize(imagenet_stats)

data = get_data(size=128)

data.show_batch(3)

acc_02 = partial(accuracy_thresh,thresh=0.2)
fbeta_02 = partial(fbeta,thresh = 0.2)
metrics = [acc_02,fbeta_02]

learn = cnn_learner(data,models.resnet50,metrics=metrics)

learn.lr_find()
learn.recorder.plot()

learn.fit_one_cycle(10,3e-02)

learn.save('small-1')

learn.unfreeze()
learn.lr_find()
learn.recorder.plot(skip_end=15)

learn.fit_one_cycle(8,slice(1e-06,1e-04))

learn.save('small-2')

data = get_data(size=256)
learn.data=data

learn.freeze()
learn.lr_find()
learn.recorder.plot()

learn.fit_one_cycle(8,1e-02)

learn.save('Big-1')

learn.unfreeze()
learn.lr_find()
learn.recorder.plot(skip_end = 15)

learn.fit_one_cycle(8,slice(3e-06,2e-04))

